CXXFLAGS=-ggdb -std=c++11 -Wpedantic -Wall -Wextra -Wzero-as-null-pointer-constant
all: main.cpp
	g++  $(CXXFLAGS)  main.cpp  -o  main
clean:
	echo -----------------------------removing executable-------------------
	/bin/rm main


