main: orderedLists.cpp
	echo -----------compiling orderedLists.cpp to create executable program main----------
	g++ -ggdb -std=c++11 orderedLists.cpp -o main
clean:
	echo -----------removing main----------
	/bin/rm main
