CXXFLAGS=-ggdb -std=c++11 -Wpedantic -Wall -Wextra -Wzero-as-null-pointer-constant
all: main.cpp
	g++  $(CXXFLAGS)  main.cpp  -o  kruskals
clean:
	echo -----------------------------removing executable-------------------
	/bin/rm kruskals


